### ISSUE TITLE
It is not possible to search for cached music when activating the airplane mode

### ISSUE THREAD

**Issue by MyNameIsTroll** [daneren2005/Subsonic#1034]
Hello,
I found that when I was in airplane mode and I was doing a search in Dsub (for example I want to listen to an artist I know I have cached) the search function doesn't work.

I'm not a developer (excuse me if I'm talking nonsense) but it seems that the application only tries to contact the server for the search whereas in this case of use the music I'm looking for is already on my device and therefore it doesn't return any results.

**Comment by SteveDinn** [comment]
This seems like it could also be useful even if the app was still online and if there happened to be cached content that was no longer on the server for whatever reason.

**Comment by daneren2005** [comment]
That is what Offline mode is for.  Honestly it might have been good to implement it like you are talking about instead of having an explicit online vs offline mode, but at this point it would require a major rewrite of the online/offline functionality to support that which I have no intention of doing.  I am mostly only doing quality of life improvements and minor feature enhancements at this point.
