### ISSUE TITLE
Files will not play if tag contains "/" character

### ISSUE THREAD

**Issue by iang77** [daneren2005/Subsonic#1041]
I am running Android 10, Dsub 5.5.1., using the SD card to store media rather than the phone's internal storage. I'm using Navidrome server (v0.39) (I don't recall this happening with Airsonic but I no longer run an Airsonic server so can't check).

What seems to happen is when Dsub is set to cache tracks, anything with a "/" in the tag will not play. If caching is turned off the tracks will play. Looking at the SD card a new sub folder is created (i.e. if the song name tag is "Apples/Oranges" then a folder called Apples is created then a sub folder inside called Oranges). Not sure if this is expected behaviour.

**Comment by daneren2005** [comment]
I would bet this is probably an issue with the differences in how Navidrome returns results vs stock Subsonic, but I would be willing to at least take a look into it.  If you email some temporary credentials to dsub.android@gmail.com I can debug the issue.

**Comment by daneren2005** [comment]
Adding your comments minus the server info from your email so I can better track this in one place:

```
 Here's a couple of examples of tracks that have the issue:
Godspeed You! Black Emperor - Lift your Skinny Fists Like Antennas to Heaven (all the tracks, there is a lot of "/")
Anne Muller - Heliopause - "Aarhus / Reminiscences"

But interestingly the tracks that contain "/" on Bernard Herrmann - North By North West don't seem to have the issue. 
I've tried removing the "/" from the filename on the Godspeed tracks but it had no effect if the tag still had the "/" in it.
```

One of the example children returned from the server:
```
<child id="55798211c0cbb88aa39e21a5cb6b37ad" parent="8de7904879fcdd721f0db07210bac4ad" isDir="false" title="Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way" album="Lift Your Skinny Fists Like Antennas To Heaven" artist="Godspeed You! Black Emperor" track="1" year="2000" genre="Rock" coverArt="al-8de7904879fcdd721f0db07210bac4ad" size="54102146" contentType="audio/mpeg" suffix="mp3" duration="1352" bitRate="320" path="Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way.mp3" discNumber="1" created="2014-04-26T23:29:31Z" albumId="8de7904879fcdd721f0db07210bac4ad" artistId="ce13052cb6d1b612467040d837c76d91" type="music" isVideo="false"/>
```

I am not able to reproduce the same issue.  On my phone all of the files from "Lift your Skinny Fists Like Antennas to Heaven" for example were downloadable and playable.

I am guessing the issue is coming from the fact that some paths in the code are trying to use the path listed in the child entry.  In this case that path is completely not valid.  Stock Subsonic will never return a path like that, because in Subsonic that is the literal path to the file on the server.  This server *appears* to be generating a path based on the file tags, which is generating bad data.  Looking through it I don't think this is something I can really fix while maintaining compatibility with other Subsonic servers that implement it the other way.  The server needs to be changed replace all of those dashes in the filename in the path to be something else like a "-".  For example instead of `Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm...` it should be something like `Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven - Gathering Storm - "Welcome To Barco Am-Pm...`.

For example here is it returned by Subsonic based on the tags:
```
<song id="17210" parent="17211" isDir="false" title="Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way" album="Lift Your Skinny Fists Like Antennas To Heaven" artist="Godspeed You! Black Emperor" track="1" year="2000" genre="Rock" size="54102146" contentType="audio/mpeg" suffix="mp3" duration="1352" bitRate="320" path="Testss/Storm Lift Yr.mp3" isVideo="false" playCount="0" discNumber="1" created="2020-12-31T23:52:35.000Z" albumId="1286" artistId="478" type="music"/>
```

**Comment by iang77** [comment]
ok, thanks for investigating.

Ian
________________________________

**Comment by iang77** [comment]
Quick update - Deluan @Navidrome suggested i enable "report real path" in Navidrome for DSub, which has resolved it. In case anyone asks again...

Cheers
Ian


Get Outlook for Android<https://aka.ms/ghei36>
________________________________
