### ISSUE TITLE
[FR] Let more songs in the history playlist

### ISSUE THREAD

**Issue by awsms** [daneren2005/Subsonic#1060]
Could it be possible to add a custom value for the "Keep played songs" value?
Otherwise, the "repeat playlist" option is basically useless. Unless I'm missing something here you can only keep the last 3 tracks played.
When you repeat an album, you'll be able to replay only the last 3 tracks in loop.
https://i.imgur.com/DbTZbEu.jpg

Another issue, but quite small so I didn't consider making an issue for this one, asterisks (*) in tracknames are replaced with dashes (-) which mess up my scrobbles. This isn't an airsonic issue since it works as expected with ultrasonic
https://i.imgur.com/vspeXt2.jpg
https://i.imgur.com/3stgqIy.jpg

**Comment by daneren2005** [comment]
IIRC that setting is only for when doing a global shuffle.  Repeat playlist would never do anything in that mode since the whole point is that it continually grabs more songs as you go so it would never get to the end of the list anyways.  That setting should have the verbiage improved to make that more obvious.

**Comment by awsms** [comment]
I was talking about playing an album in repeat (video illustrates it)
https://share.riseup.net/#AJWC0AB1SmntgtQ3NYewDQ

I guess there is no way then ?
