### ISSUE TITLE
cache location

### ISSUE THREAD

**Issue by FacialLeather** [daneren2005/Subsonic#1091]
Today I noticed that I cannot change my cache location. Even when I use the the internal or external default locations and DL some music, those music files are nowhere to be found on my phone. 

And these are the errors I get if try to create folders within the default cache directories:
**Internal**  "operation failed"
**External**: "error occurred try again" 

For context, I have had my music stored in 'SD card/Android/Music' for years now without issue. Now when I go offline, my dsub library is blank but all of my music is in that folder. 

These are the cache locations provided by dsub:
**Internal**: /storage/emulated/0/Android/data/github.daneren2005.dsub/files/music
**External**: /storage/7C56-15F0/Android/data/github.daneren2005.dsub/files/music

I have cleared the app's cache and restarted my phone. 

Are we no longer able to change the location?

Why cannot I see my offline files in dsub?

Thank you

**Comment by tordenflesk** [comment]
Long-standing known issue, preventing me from reasonably backing up app-data due to the fact the music being stored as app data...

**Comment by FacialLeather** [comment]
It just began happening with me in Feb/early march. Maybe due to an android or samsung update during that time? 

So the music is there but not viewable?

**Comment by FacialLeather** [comment]
> Long-standing known issue, preventing me from reasonably backing up app-data due to the fact the music being stored as app data...

I seem to have fixed it, but maybe it will change in the future. Where you can change the location in the dsub app, I redirected it to /download/Subsonic, where 'download' normally defaults to 'Android/....". This was on my SD card. Hope it works for you.

**Comment by FacialLeather** [comment]
Sooo...Not as big of an issue, but now when I delete cache via dsub, the files still remain in my sd card folder. I changed the cache location (**to the phone HD**) to download/subsonic, and same- cache will not delete after 'delete cache' via dsub **(even after force stopping and clearing app cache in android app settings**). Beggars can't be choosers, or is there a fix I am not seeing? 

_**UPDATE**_: I spoke too soon...deleting song file cache in dsub app now removed it in my android folder. This may have something to do with deleting all files in the android folder an downloading/caching again from subsonic.

**Comment by melectronvolt** [comment]
Same here with Samsung Galaxy Note 10+, airsonic 11 and the last version of Dsub. Don't know if it's android 12 permissions or anything else but I can"t change location to anything other than /storage/xxxx-xxxx/Android/data/github-danere....

It's a shame cause I wan't to have the cache accessible by other apps, which is impossible in this case.

**Comment by FacialLeather** [comment]
Did you try what I said in my most recent post beginning with "Sooo...Not as big of an issue, but"? I have an S10+, Android 12 with subsonic. I've never tried airsonic. What's the diff between (or advantages with airsonic) subsonic and airsonic?

**Comment by melectronvolt** [comment]
Airsonic is an open-source advanced version of airsonic. But the problem comes from DSub, in the last version available on google store I can select any directory to store the cache (and I can access my music files with other players). Not in the last version.

**Comment by flamingspaz** [comment]
Since Android 11, Google has enforced the use of SAF Scoped Storage. A few months ago, all new builds pushed to the play store are forced to use it, but because dsub hadn't been updated since 2020 it was safe until the last update.

You can only choose the default internal/external folder, and Android does not allow any apps to view the contents of these folders. Also, if you use an SD card, expect things to be significantly slower. SAF Scoped Storage is [pretty terrible](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/).

There's one workaround and two (really one) solution
* Workaround: Change your path to a folder inside your `Download` folder. This is pretty buggy and you can't add any external files anyway.
* Upload a version to f-droid which doesn't use scoped storage
* Convince Google that this is a document management app (unlikely to happen)

**Comment by GEkuL** [comment]
@FacialLeather has the issue been resolved or we need some software side fixes?

**Comment by FacialLeather** [comment]
It's been working since my last comment. I created the dsub folder under sd card/Downloads/dsub and deleting song file cache in dsub app now removed it in my android folder. This may have had something to do with deleting all files/cache in the android folder an downloading/caching again from subsonic sever. So all set!

**Comment by FacialLeather** [comment]
Per a previous comment, perhaps my music or the folder it was in was corrupted for some reason or due to an Android or Samsung update. Just a theory

**Comment by GEkuL** [comment]
@FacialLeather 
Happy to hear that!)

So if there're no any other question or points to discuss, could you close the issue since it seems to be resolved?

**Comment by dessalines** [comment]
This needs to be re-opened, as its still broken. Android now needs specific folder permissions to be able to use another folder.

**Comment by zblesk** [comment]
I've tried downgrading to the previous version (on Android 12), but it hasn't helped. Seems there also aren't any additional file permissions I can grant manually. 
Pity, because using DSub to get files to my phone was my primary use-case. 

Does anyone monitor closed issues? Or should we create a new one?
