### ISSUE TITLE
Using Dsub with Android Auto

### ISSUE THREAD

**Issue by phirestalker** [daneren2005/Subsonic#1145]
I have used Dsub with Android Auto before when I installed it from the play store. The version in the play store is really outdated now and I have switched to getting the app from f-droid. I have enabled developer options and other sources in the Android Auto settings. Dsub still does not show up in the list of apps I can add to the launcher. What do I have to do for the f-droid version to work with Android Auto?

**Comment by curiousercreative** [comment]
@phirestalker any luck? I also install from F-Droid and I don't even see an app listed in Google Play Store (incompatible with my device?). I do see that there's an API labeled google release here that's up to date. Have you tried that? I'm looking into Android Auto head units and will want to stream from DSub Offline. https://github.com/daneren2005/Subsonic/releases/tag/5.5.3

**Comment by phirestalker** [comment]
> @phirestalker any luck? I also install from F-Droid and I don't even see an app listed in Google Play Store (incompatible with my device?). I do see that there's an API labeled google release here that's up to date. Have you tried that? I'm looking into Android Auto head units and will want to stream from DSub Offline. https://github.com/daneren2005/Subsonic/releases/tag/5.5.3

Sorry, I gave up. I paid for d-sub from the play store, but it wasn't worth the effort to try to fix this.

**Comment by curiousercreative** [comment]
Hmmm, DSub music will play through the latest Android Auto, but there's no UI on the car screen at all. I tried both the latest F-Droid and GitHub releases with the same results.

**Comment by FacialLeather** [comment]
I don't have Android Auto but ever since Chromecast came out I noticed that D-Sub cannot be chosen as a default service in Google Home, unlike Spotify and others. I am not invalidating your question, I just learned to live with it and didn't find it as big of a deal but I understand where you're coming from. I'm not a programmer or even close so assuming Google (as well as Amazon Alexa and Apple) only connects with the big services, for whatever reason.
