### ISSUE TITLE
Add option to play "Smart Playlist"

### ISSUE THREAD

**Issue by ssarna1** [daneren2005/Subsonic#1155]
Owncloud / Nextcloud music added recently smart playlist options in v 1.9.1.

**Comment by paulijar** [comment]
This is more of a server-side requirement and there is already an open issue for this on ownCloud/Nextcloud Music: https://github.com/owncloud/music/issues/1097

The server could pretend that the smart playlist is just a normal playlist and expose it via the Subsonic API in which case the client wouldn't need any specific support for this. This is of course still sub-optimal because it doesn't allow the user to define the rules of the smart list using the Subsonic client. But as there is no support for such feature in the Subsonic API specification, there's little that DSub as a generic Subsonic-compatible client can do to improve the situation.

**Comment by ssarna1** [comment]
You're right, i guess this can be closed now. If this is added do server, then we might think about controlling it somehow (generating new playlists or changing settings) if Subsonic api even allows for that.
