### ISSUE TITLE
4.3.6 - Double scrobbling to Last.FM

### ISSUE THREAD

**Issue by nRaecheR** [daneren2005/Subsonic#256]
There is a new bug introduced with 4.3.6 in the Last.FM scrobbling functionality. Until this version the server scrobbled the song to Last.FM, now DSub uses the Android Last.FM app installed on the device to scrobble it too. This leads to two scrobble for each single song.

**Comment by danielmorse** [comment]
A simple 'only scrobble from the web player' would solve this.

**Comment by danielmorse** [comment]
Seems like this would be best handled on the server side, not inside DSub. The server should have an option to only scrobble from the web client and nothing else, allowing scobbling to be handled by each non-web player.

**Comment by daneren2005** [comment]
That would be a terrible feature since part of the point is you don't have to enter your Last.FM credentials on every app. And it wouldn't affect this problem at all. This is a problem of the Last.FM app listening for media player events and scrobbling on its own without being told to and there being no way to turn it off without uninstalling the stupid app.

**Comment by danielmorse** [comment]
I would much rather go around and enter all my details into every audio player (or in the case of my phone into the last.fm app once) rather than having to go to either my subsonic server and or the last.fm app and turn scrobbling off on one of them every time I want to use subsonic (I also use google play on my phone and I want to be able to scrobble from that as well, hence the need to have the last.fm app on my phone). Obviously another solution would be to have a way to tell the last.fm app to ignore DSub, but I have a gut feeling that the last.fm team is not as responsive as the subsonic team.

**Comment by danielmorse** [comment]
BUT I would like the subsonic server to scrobble for me when I am using the web interface.

**Comment by danielmorse** [comment]
Should have done a check of github first. Looks like there is an open source scrobbler out there. it might just be better to use that since it does not seem to support DSub.

**Comment by daneren2005** [comment]
Then turn off the scrobbling in DSub. It is literally the first comment in this issue thread...

**Comment by danielmorse** [comment]
My apologies. By 'in the app settings' I thought you meant on the server. Ignore everything I said.
