### ISSUE TITLE
Chromecast - "Unable to load"

### ISSUE THREAD

**Issue by SUTJael** [daneren2005/Subsonic#367]
Hi @daneren2005,

We already spoke in the #320 about self-signed certificate. I was receiving the same message "Unable to load" but I was thinking that it was due to the certificate (https). So I decided to test without SSL (http) but I'm still getting the same error message.
When I disconnect from the chromecast the song is played correctly.
DSub version is 4.6.5.

Thanks.

**Comment by PeterBehrend** [comment]
-hi,
Not sure if you read a new entry to a very old thread. Let's see :-)
I thought I would never see the dreaded "Unable to load" message again. Unfortunately I get it all the time now. My setup is much like the above mentioned (Ampache with Subsonic header rewrites applied and Chromecast). Worked for years now, Until I bought the "Chromecast Audio" device. *SIGH*
Now it's the same. "Unable to load" all the time. And it "hangs" dsub and makes my phone VERY hot because of some nasty kind of software loop. This is not criticism. Problem might as well be in the "Ampache -> Subsonic header rewrite rules". But I can't figure it out. The strange thing though is that SOMETIMES it works without a flaw. And then suddenly this problem pops up. I then need to reboot my phone to kill rouge processes. My Dsub version is 5.3.2. 
kind regards
/peter
