### ISSUE TITLE
Share link incomplete

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#482]
Things have been fixed with Ampache, so now I have the option to create a share link from DSub.  However, I noticed that the resulting URL is incomplete.  I'm only getting URLs like:

https://xxx.xxxxxxx.com/ampache/share/share.php

In comparison, with Utrasonic, I get:

https://xxx.xxxxxxx.com/ampache/share/share.php?id=32&secret=kD1sJko5

**Comment by daneren2005** [comment]
It was due to Ampache giving the share url in a different form and Subsonic needing a work around.  In Subsonic that share url is sometimes broken (ie: always listed as http, sometimes listed as the user's *.subsonic.org if they have one even though they aren't connecting through that, etc).  I just chop off the entire http(s)://***/share/ and replace it with what it should be.  The problem is that Ampache wasn't giving the url as /share/ it was giving /share.php.  I fixed it by just not doing any url fixing when .php is in the url.

**Comment by dhsc19** [comment]
Thank you!  I will also contact Ampache dev about making Ampache's Subsonic API more compliant.

**Comment by daneren2005** [comment]
Since the /share/ is not a part of the official API, returning a different style of url seems mostly compliant to me.  I honestly don't see that particular part to be a problem.

**Comment by dhsc19** [comment]
Thanks.  The new update has fixed the problem.  In Ampache, when a shared object is created, the shared object is usually labeled either by the album title or song title.  Right now, the shares are initially created showing up as "share.php" in DSub even though it has an Object name in the web interface.  I can update DSub by updating he name information, but I'm wondering if Ampache should have been able to supply that information initially but not supplying the correct parameter.  If you could let me know what is missing I will report to Ampache dev.
