### ISSUE TITLE
Show Artist and Show Album going to the same album info screen

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#487]
When I press on the track menu:

![screenshot_menu](https://cloud.githubusercontent.com/assets/10291198/7028502/0ca1f0ce-dd0b-11e4-8f78-fc4ab3d476a5.png)

These two choices:

![screenshot_show](https://cloud.githubusercontent.com/assets/10291198/7028567/7f41332e-dd0b-11e4-8813-273c89b3d71c.png)

Take me to the same screen:

![screenshot_2015-04-07-09-47-35](https://cloud.githubusercontent.com/assets/10291198/7028576/8ce90a24-dd0b-11e4-8b5b-443788153380.png)

I would have thought that Show Artist would take me here, instead:

![screenshot_2015-04-07-09-48-16](https://cloud.githubusercontent.com/assets/10291198/7028589/a5966030-dd0b-11e4-947f-8a95d174ee1d.png)

Bug?  Maybe another Ampache/Subsonic API compatibility issue?

**Comment by daneren2005** [comment]
Definitely a Ampache issue.  The artist and album ids are the same:

    <child id="200001419" album="Beyond" title="Beyond [2007]" name="Beyond" isDir="true" coverArt="200001419" songCount="11" duration="2968" artistId="100001215" parent="100001215" artist="Dinosaur Jr" averageRating="0"/>

I think I'm going to give Ampache a try as a Subsonic replacement after they are done fixing all of these little issues :D

**Comment by dhsc19** [comment]
Yeah.  DSub and Ampache make an excellent music server/mobile client combination.  I've certainly appreciated the active development and collaboration of both sides.

So, the fields we're talking about here are "album" and "name"; and "name" should be the name of artist.  I will open a ticket with Ampache.

**Comment by Afterster** [comment]
@daneren2005 what do you mean about artist and albums ids are the same?
I'm not sure to understand but in you example the album id is 200001419 whereas artist id is 100001215. Nop?

**Comment by daneren2005** [comment]
Ack, I am sorry.  I was in a hurry and came up with the entire wrong reason because it was what I expected to be wrong.  I saw `artistId="100001215" parent="100001215"` and jumped to the completely wrong conclusion.  Upon further inspection, the issue appears to be that in ampache there is no parent id listed on the directory.

For example, we start with a song:

    <child id="41079" parent="41058" isDir="false" title="Behind Silence and Solitude" album="Behind Silence and Solitude" artist="All That Remains" track="1" year="2002" genre="Metal" coverArt="41058" size="33981854" contentType="audio/flac" suffix="flac" transcodedContentType="audio/mpeg" transcodedSuffix="mp3" duration="259" bitRate="1046" path="All That Remains/Behind Silence and Solitude/01 - Behind Silence and Solitude.flac" isVideo="false" created="2015-01-29T02:12:41.000Z" albumId="3005" artistId="428" type="music"/>

We grab the parent id from that of "41058".  We then look up that id and get:

    <directory id="41058" parent="147" name="Behind Silence and Solitude">

From that we use the parent of 147 to show the artist.  It's convoluted but it was the only solution I could come up since only the parent id is given (in non-tag mode.  In tag mode I just use the albumId and artistId values).

In ampache this is the song:

    <child id="300015042" parent="200001419" title="Almost Ready" isDir="false" isVideo="false" type="music" albumId="200001419" album="Beyond" artistId="100001215" artist="Dinosaur Jr" coverArt="200001419" duration="188" bitRate="320" track="1" year="2007" genre="Indie Rock" size="7603792" suffix="mp3" contentType="audio/mpeg" path="Dinosaur Jr/Beyond/01 Almost ready.mp3" transcodedSuffix="ogg" transcodedContentType="application/ogg"/>

Lookup parent id "200001419" and get:

    <directory id="200001419" name="Beyond [2007]">

It is missing the parent id so there is no way for me to figure out what artist I am supposed to be displaying so I just display the album.
