### ISSUE TITLE
Can't stream using HLS

### ISSUE THREAD

**Issue by skug67** [daneren2005/Subsonic#551]
Using DSub 5.0.2 (with Madsonic 5.1) I can stream videos fine using direct transcode or raw.  But when I try to use HLS (which I'm hoping wll allow seeking in high-bitrate files that I can't do with direct transcoding) it fails and when I turn on debug logging I see the following error repeated multiple times on the server --  INFO RESTRequestParameterProcessingFilter - Authentication failed for user null.

Anybody have an idea what's going on and how I can fix it?

Thanks in advance,

Seth Green

**Comment by daneren2005** [comment]
Works with stock so probably a madsonic issue

**Comment by skug67** [comment]
Actually, turns out I can get the stream working if I install MX Player.  I had been using VLC and the problem must have been something about how VLC passes the URL requesting the HLS stream back to subsonic/madsonic.  On the negative front, if I try to seek through the stream the video just hangs and never restarts.

**Comment by daneren2005** [comment]
vlc probably strips all the params off or something silly like that.  I have never been able to get seeking working using Subsonic.  Their hls streams aren't valid or aren't what players are expecting.  I have mostly given up on video using Subsonic since the server developers need to fix whatever is wrong with them and they won't.
