### ISSUE TITLE
Album art not updated after being changed in Subsonic

### ISSUE THREAD

**Issue by agn4965** [daneren2005/Subsonic#611]
The album art doesn't get updated in the song list, or the now playing view. The now playing bar does show the new, correct art however.

I had to clean up the subsonic database and scan media folders to resolve this issue.

**Comment by daneren2005** [comment]
I will only be partially fixing this.  I will be updating stuff to better respond to the changing of the coverArt id, but this only appears to update when going from no cover art to having cover art or vice versa.  I tried updating the cover art and Subsonic does not update the coverArt id so I have no idea whether it has changed without downloading the entire thing.  I refuse to make it have to download every cover art in the background just to check if they have been updated since it defeats the entire purpose of a caching system (ie: sane data usage).  If cleaning & rescanning fixes it, I imagine that cleaning wipes out all of the coverArt id's and that is a issue with the server.
