### ISSUE TITLE
songs in top rated dont play 

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#621]
when you rate a song it shows up in the top rated list in home menu but when you click on it it says no data.  but  it works for albums  but not for songs.  the song shows up like an album but couldn't be played it says "no data"

**Comment by daneren2005** [comment]
I'm guessing you aren't using stock Subsonic? Only albums are supposed to show up there in the first place...

**Comment by addisflava** [comment]
Am using madsonic. 5 .

**Comment by addisflava** [comment]
It is it possible to add song rating . I realu dont understand why  everything is center around album . I think top rated , most played stared  feauters make more sence in songs more than albums . It is easy to remember an album  browse to it . Madsonic has a lot of new features that support songs

**Comment by daneren2005** [comment]
`<album id="7870" parent="7869" rank="0" isDir="false" title="Brandenburg Concerto No. 5 In" album="The Bach Collection" artist="Bach" track="1" year="1994" genre="Classical" coverArt="7869" size="14378880" contentType="audio/mpeg" suffix="mp3" duration="599" bitRate="192" path="Bach/The Bach Collection/Bach - Brandenburg Concerto No. 5 In D Major -Allegro 1.mp3" isVideo="false" userRating="5" averageRating="5.0" created="2013-12-05T10:19:11.000Z" albumId="518" artistId="372" type="music"/>`

Mad in all his brilliance decided to make songs showed up labeled as albums breaking the default behavior.

**Comment by addisflava** [comment]
Now the songs are displayed as songs but do not play , when u select a song it just jump to the next album ,  it is also very unorginized the way the  songs and albums are displayed .

**Comment by daneren2005** [comment]
It actually is playing, it is just added later. The problem is due to the play after behavior. With just songs you click on a song and it starts at that song and adds all the songs after to the list to continue on after. It is pretty broken with albums in the list as well. It's never come before because everywhere else the albums are listed first then the songs. I will definitely fix it in the next release since the play after behavior doesn't even really make sense in a albums list anyways.

As for the ordering that is up to Madsonic. I can't just sort it albums then songs because I only load 20 at a time and just load more as you scroll down. I hope it's obvious why that wouldn't work with trying to apply my own sorting.
