### ISSUE TITLE
Cache: Better Storage Limit Settings

### ISSUE THREAD

**Issue by luckydonald** [daneren2005/Subsonic#640]
The cache is missing some more subtile settings:
 - [ ] Minimum disk space to keep free (e.g. 100mb free space)
 - [ ] Maximum files to keep (e.g. 100 Songs)

 - [ ] Auto delete songs, e.g.
     - [ ] last played
     - [ ] last added

Also some UI improvement would be good:
 - [ ] Folder chooser for the path
 - [ ] Slider for the size
   - as for the maximum value: maybe the overall storage capacity (free+full) and highlight the free space green and the full space red?

**Comment by daneren2005** [comment]
I really have no intention of implementing any of this stuff.  Every single piece of code does not need to have a user toggle for it.  It makes it a nightmare to maintain and hunt down bugs, and rarely benefits more than a couple of people.

There was already another issue open for a folder chooser for the path and I instead went with just adding buttons for the couple of valid options.  On later versions of Android they are the only really valid spots to put music and I see little reason to be placing music anywhere else.  If you want to be micro-managing the location you can manually enter the path.

Slider: I actually implemented this at one point and ended up reverting it because in practice it makes it much harder to define a specific value instead of just typing it in.

I see little reason to implement a maximum files to keep vs a max storage to keep since the limiting factor in reality is storage space, not files.  I understand some may want it that way anyways, but back to point #1 that everything can't be an option just for options sake.  It becomes unsustainable to support.  DSub is designed around storage space and will remain that way.

I think the minimum disk space to keep free is the only logical change, but even that is silly to make it configurable.  Systems become unusable if they go below a certain amount of space and that isn't something up to the user.  If you want it lowered to say 200MB I would consider that if you want to open a separate issue.  But I am not making it a separate user option.

**Comment by luckydonald** [comment]
Right now my phone ends up with 0KB left **all the time**.
If I set the space to a lower value, I can't see any removal of files happen.
Notice, I set it to ~3 GB, but it uses ~10 GB.
See screenshots.

![bildschirmfoto 2016-02-23 um 23 20 38](https://cloud.githubusercontent.com/assets/2737108/13268692/3a3618fe-da84-11e5-9856-d2cd5bc08d25.png)![bildschirmfoto 2016-02-23 um 23 21 08](https://cloud.githubusercontent.com/assets/2737108/13268697/403e9550-da84-11e5-9149-bad1d018b58b.png)![bildschirmfoto 2016-02-23 um 23 19 18](https://cloud.githubusercontent.com/assets/2737108/13268702/45886be4-da84-11e5-9014-45ac419dd57f.png)

**Comment by luckydonald** [comment]
It even warns me that only **200 KB** are left, but continues downloading until **0 B** are left.
Still it wants to download another file. This doesn't feel like intended.
![bildschirmfoto 2016-02-23 um 23 28 57](https://cloud.githubusercontent.com/assets/2737108/13268899/4c666352-da85-11e5-8533-55abdac3f04f.png)

**Comment by luckydonald** [comment]
Have an use case example for a minimal storage setting:
You will go on an holiday tour, and want to have, say, 2 GB free space to be able to make photos. It doesn't need to watch that space all the time as background progress. But when a new file is about to be downloaded that should be taken into account.
This app is about caching, which is great. But "until the storage is full" makes the rest of the phone unusable.

**Comment by daneren2005** [comment]
Alright so it sounds like something with the minimum storage space is not working correctly.  It should require a minimum of 500MB stays available (see I thought you wanted to have a lower amount).  Open another issue with a title "Minimum File System Space Not Working" or some thing like that.  I am not sure of your knowledge of Android.  If you know how to use logcat in the new issue you open add the logs from CacheCleaner.  If you don't know how to use logcat follow these directions so I can get the necessary logs:

Swipe DSub out of memory
Open it up
Immediately go to the Home tab -> Send Log

**Comment by daneren2005** [comment]
You ever get a chance to look at this?

**Comment by luckydonald** [comment]
I cleaned the cache from DSub's settings, and deleted the folder contents too. Still I ended up with 0 KB.

> You ever get a chance to look at this?

To be honest, I bought a iPhone instead and went with iSub...
