### ISSUE TITLE
Can't gather logs

### ISSUE THREAD

**Issue by popeen** [daneren2005/Subsonic#644]
You might want to have a look at this, it seems to be present in the latest DSub release as well popeen/Popeens-DSub#35

**Comment by daneren2005** [comment]
You have to put a Pastebin key in https://github.com/daneren2005/Subsonic/blob/master/app/src/main/java/github/daneren2005/dsub/util/EnvironmentVariables.java.  I am not making mine public because it has a limited number of submits.  At some point I did an emergency bug fix release from my laptop and forgot to put my key in there so that is why it is failing for normal DSub builds right now as well.

The rational behind this is I am tired of getting constant log emails where the logs failed to attach for unknown reasons.  It was never reproducible on anything I own so I could never figure out what was going on with that.  Users were usually able to manually go and attach the files though I know they were being generated correctly.  Using Pastebin should get around this issue.

**Comment by popeen** [comment]
Yeah, I know you have to use an API key, thats not the problem, I have a
key in my releases as well. It works when I use it on my phone (6.0.1) but
I have a couple of relatives that have 5.0 phones and both of them get the
error.

Since I don't have their logs yet I don't know what the problem actually is
but since they both have 5.0 I'm guessing that might have something to do
with it.

The DSub release I told them to test is 5.1.4 (from github) which works for
me so I don't think the key is missing.

Closed #644 <https://github.com/daneren2005/Subsonic/issues/644>.

—
Reply to this email directly or view it on GitHub
<https://github.com/daneren2005/Subsonic/issues/644#event-544650302>.

**Comment by daneren2005** [comment]
I can reproduce on a old 4.3 device.

**Comment by popeen** [comment]
If you move where urlConnection is closed in getLogs so it's closed after you get the response it seems to work. See popeen/Popeens-DSub@a9ecb245494b764a0393d25fb4d3526549bc7d10

**Comment by daneren2005** [comment]
Yeah I found the same thing
