### ISSUE TITLE
Podcast cache is being deleted and resulting bookmark becomes invalid

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#659]
It doesn't seem to matter if I manually "cache" or "permanent cache" or let the app automatically cache a podcast as I am playing it.  It seems that after I stop or pause a podcast playback and playback something else, the podcast cache is deleted.  This leads to the problem of the resulting bookmarks.  When I try to go back to a podcast bookmark, I get the messages "The requested data was not found".  I cannot get rid of the pop-up message.  I press OK and it comes back.  I cannot do anything else on the app when that happens.  I have to go to the phone's app manager and force stop the app and clear cache.

**Comment by daneren2005** [comment]
Cache and bookmarks should only be deleted if you are close to the end of the podcast. Is it not doing that?

**Comment by dhsc19** [comment]
It is deleting when I finish to end.  The problem is, I could be listening a few minutes into a 1 hour podcast.  Pause it, see that a bookmark has been made.  Then, when I listen to something else (another podcast for example), the previously listened podcast "cached" status disappears even though the bookmark for it still exists.  When I try to play from the bookmark list, I get the "requested data was not found message".  In fact, when I play the podcast again (not from the bookmark) the app re-downloads the file.  But, I'm searching Ampache's issues list and this may be a problem in Ampache.  I will close this for now.  The podcast feature in Ampache is relatively new, so I may have to wait for it to mature a bit more.

**Comment by daneren2005** [comment]
I do see an issue where Podcast cache can be deleted even when it is set to Permanent Cache.  I will fix that since it should only auto delete if only temp cached.  As for it deleting the cache but not the bookmark, that is a strange one.  The logic appears to be the same for both, so if the cache is deleted the bookmark should also be deleted.  I imagine there is some funniness with the metadata from Ampache.  I will have to take a look at it.  Is the access to your server from https://github.com/daneren2005/Subsonic/issues/622#issuecomment-170458557 still valid?

**Comment by dhsc19** [comment]
I've re-enabled the user account.

**Comment by daneren2005** [comment]
Ampache does not appear to display Bookmarks at all in the Podcasts list.  I tried refreshing the list after a createBookmark call from pausing on a podcast and it doesn't show on the podcast.  Going to Bookmarks it shows up though.

As for the infinite error, apparently I did not wrap the Artist image loading in a try/catch block, and it is failing on Ampache.  It should not have even gone down that path in the first place.  It appears that in the metadata returned from Ampache for the getBookmarks method, it does not include a `parent` so DSub thinks it is a artist in disguise (I can't even remember why I had that logic at this point).  But it also means that the Show Album/Show Artist functions will not work so it should be fixed in Ampache either way.

ie: ```<bookmark position="2299" username="scott" comment="" created="2014-10-15T15:15:18.272Z" changed="2014-10-15T15:15:18.272Z">
    <entry id="29819" parent="26083" isDir="false" title="Tie Your Mother Down" album="A Day At The Races" artist="Queen" track="1" year="1976" genre="Rock" coverArt="26083" size="31603629" contentType="audio/flac" suffix="flac" transcodedContentType="audio/mpeg" transcodedSuffix="mp3" duration="288" bitRate="877" path="Queen/A Day At The Races/01 Tie Your Mother Down.flac" isVideo="false" playCount="9" created="2013-02-27T21:21:35.000Z" albumId="1687" artistId="370" type="music" bookmarkPosition="2299"/>
</bookmark>```

**Comment by Afterster** [comment]
Always watching with interest, don't hesitate to HL my username when it's an Ampache-related bug.
On Ampache, Podcasts don't have artist information.

`Ampache does not appear to display Bookmarks at all in the Podcasts list. I tried refreshing the list after a createBookmark call from pausing on a podcast and it doesn't show on the podcast. Going to Bookmarks it shows up though.`
 => What should be the excepted xml response here?

I will fix the missing parent information on podcast episodes otherwise.

Thank you.

**Comment by daneren2005** [comment]
If there is a bookmark the bookmarkPosition field should show up when loading the entry anywhere else as well. This includes on the podcasts tab.
