### ISSUE TITLE
new feather:  

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#666]
Hi there 
I would like to see dsub open shared songs on social media or sms directly without browsing share by just clicking on the share  . currently when you share it shares the subsonic url which directs users the  the subsonic page even if you have dsub,  which is not ideal since its not mobile friendly and uses flash 

I think  using a different sharing option for dsub and creating  an intent on dsub which will listen . when a user shares a song it creates a share with  an intent and the song as parameter and  dusb will launch search for the song on dsub and show the result .
what do u think ?

**Comment by daneren2005** [comment]
I don't intend on adding this. DSub is way to small of the percentage of users to be worth making a share which only works on DSub. I can only register for intents at compile time and since every subsonic site is going to have its own unique url I can't really add a generic intent receiver for this.
