### ISSUE TITLE
Resume playing after interruption

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#668]
For example if I were to play an embedded video in my browser or in the YouTube app and dsub gets paused, could dsub resume playing after the video stops playing?

**Comment by daneren2005** [comment]
No.  The only way I know that an app is done is if it releases media focus.  Most apps won't actually do that until they are fully closes causing weirdness.  I had this enabled at one point and ended up taking it back out because so many apps just made it so that DSub would start playing at seemingly random times.
