### ISSUE TITLE
Playing queue not always synhronised to server

### ISSUE THREAD

**Issue by KBanause** [daneren2005/Subsonic#684]
When using the web player of subsonic I can save the playing queue to the server and DSub will ask me if I want to continue listening to my saved playing queue. Unfortunately DSub doesn't always save the current playing queue to the server so I can't continue listening when using the web player again.

**Comment by daneren2005** [comment]
I would need some more information since it appears to save every time for me.  Next time it happens, can you try pressing play and then pause on the phone to see if that fixes it?  If it doesn't, send me a log via Home -> three dot menu -> Send Logs.  Because you had just pressed pause again it should have the logs I need at the top of the stack for me to look at.
