### ISSUE TITLE
Ability to disable rating/thumbs & bookmark overlay

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#699]
I'm referring to the translucent dark bar covering the album art in the now playing view, quite intrusive for something that can't be disabled.

**Comment by daneren2005** [comment]
It is only there and goes away after a few seconds.  You truly never use star, bookmark, or thumbs up/down?  I was also going to add the new variable playback speed button there.  I don't think I like the idea of giving an option to disable that since a ton of people will do it and forget about it later.

**Comment by T7000** [comment]
Nope, I've never used any of the buttons on there. I wouldn't use the variable playback speed either to be honest.

For the people that would use it: how are they supposed to make the bar show back up after it's faded out?

**Comment by daneren2005** [comment]
When you click on something it pops up back.  I honestly don't think I want to implement this.  It is a fairly integral part of the UI.
