### ISSUE TITLE
Screen freezes while scrolling

### ISSUE THREAD

**Issue by Osch-info** [daneren2005/Subsonic#806]
Here is a strange bug which I will try to explain:
If you scroll down the album list with covers and you press the back-button in the upper left corner while the list is in motion, the cover-screen freezes and every action take part **under** the freezed screen. (See Screenshot).
I really hope you can fix it!
![screenshot_20170613-085525](https://user-images.githubusercontent.com/1789289/27070011-71f3a2a2-5017-11e7-90d2-87d39dd99cc9.png)

Tested on Samsung Galaxy S7, Android 7.0

**Comment by gunslingerfry** [comment]
Happening to me as well. 
DSub: 5.3.5 
Sony X Compact 
Android 7.1.1

**Comment by rhyddic** [comment]
Still happening on DSub 5.4.4, Samsung Galaxy S9, Android 9.  I thought it was only an issue on my old LG G4, but it persists across manufacturers, Android and DSub versions. Easy to reproduce while "throw scrolling" in an album art view (i.e., Random, Recently Added) while the scrolling slows down but hasn't stopped completely, click <- within the app - will go back to the main DSub menu but leave those album art images in view on top of the screen.  Rotating the screen will clear it, but only if rotation is unlocked.  Otherwise, it seems you must exit and reopen DSub.
