### ISSUE TITLE
Latest update breaks widget on Samsung Galaxy s8+

### ISSUE THREAD

**Issue by plastikman** [daneren2005/Subsonic#885]
After the last 2 updates I am no longer able to control music with the widget on my home screen. I have reverted to the 5.4.1 release and things are working much better.  I'm not sure of you have a Samsung device but looks like 5.4.1 is the last stable release for this phone. I am on 8.0 fwiw.

Thanks

**Comment by troycarpenter** [comment]
I experience this as well.  The widget will open dSub, but won't control the music.

I think I will also go back to 5.4.1 because after that I've experienced a raft of issues (loss of focus doesn't work, widget issue, audio continues after bluetooth disconnect, multiple crashes when entering settings menu)

**Comment by troycarpenter** [comment]
Version 5.4.4 fixed the problem (and all the others I've been having), but I see it was reverting the SDK number.

**Comment by plastikman** [comment]
5.4.4 resolved the issue for me too. This can be closed out.
