### ISSUE TITLE
DSub, google auto, read error by library

### ISSUE THREAD

**Issue by didoebb** [daneren2005/Subsonic#952]
DSub, google auto, read error by library

Hello
On android the application works perfectly on Two phone.

but used with "google auto":
  the album function ... works.
But the Library function gives me access to my subonic folder, to my artist subfolders but not to subfolders albums.

If I click on an artist folder and then play, I do not have the right song.

Is this a good word for use with "google auto"?
Thank you

With my apologies for my English, I am French.

**Comment by stooge4444** [comment]
I am also experiencing this same problem.  I will attempt to do some debugging soon.  When I play a playlist or play a recent album, it's just fine.  When I navigate into a specific artist, it does not select the right songs; it select songs but from a different artist.  It does seem consistent though...when I select Acid King it plays Acid Bath...lol....but it does that every time I select Acid King.  When I use the app on the phone at the same time, it will select the correct artist.

Please let me know which pieces would be the best for debugging....but @didoebb you're not crazy!

**Comment by Koenvh1** [comment]
This could solve that issue:
https://github.com/Koenvh1/Subsonic/commit/18ae3841b716e27f76f69c43a67ccd2ae9da548c

Did not test it with Airsonic or Subsonic, so I don't know for certain.

**Comment by Buxtehude454** [comment]
I have the same issue. Relevant info, I am running Airsonic 10.6.2 (latest), and I have 2 "libraries" in my server config, one for music and one for podcasts. I am running the latest Google Play Store version of DSub, 5.5.1.

From my testing, this issue appears to be connected to the setting Settings->Servers->[My Server Name]->Browse By Tags . If I uncheck this box, I get the same behavior within the app as I get in Android Auto. Tapping an artist name under the Library brings up albums related to a different artist. As an example, in my library, tapping on "Alexander Brandon" takes me to albums by "Crowded House."

I have found a work around for this issue. Leave "Browse By Tags" unchecked in the Settings, go to Library in the Android (not Android Auto) app, and in the "Select folder" dropdown select "All folders." This seems to fix the problem. I can then set the "Select folder" dropdown back to my "Music" Library and everything works as expected, and this carries over to Android Auto as well.

If "Browse By Tags" is turned back on, the issue reappears. This suggests that perhaps the Android Auto component always uses the "non-Browse By Tags" setting regardless of what it is set to, but uses the cached Library data from the main app.

The workaround is adequate for me because I have my music organized in a directory structure, but might not work for others if you are relying on the tags for organization.
