### ISSUE TITLE
Unable to filter by library folders

### ISSUE THREAD

**Issue by timbuktumor** [daneren2005/Subsonic#953]
No matter which folder is selected to filter the music library, the end result is an "All Folders" view. 

Server is Airsonic.  Using dSub on Galaxy S9 (Android 9). 

I have two folders defined on the server; Albums and Singles.  dSub will filter properly with older Android devices, but not from the Galaxy S9.

**Comment by glennrice** [comment]
I know it's awhile since you posted this, but I have just discovered the same issue here. Two Nova 3i phones with Android 9 - one worked and one had the same issue as yourself where every folder gives "All folders".

The solution for me was to go iinto Settings --> Apps --> DSub --> Storage and CLEAR DATA.

Go back in and setup DSub again and reconnect it to your server. Folder views should work fine now.

**Comment by timbuktumor** [comment]
> The solution for me was to go iinto Settings --> Apps --> DSub --> Storage and CLEAR DATA.

What actually causes this bug is enabling the Browse By Tags option.  Settings--> Servers--> Browse By Tags.  It's not enabled by default, thus clearing the app data makes the folder selector work.  I'm assuming you had BBT enabled.  I did.  I didn't discover this until your post, so thank you for your comment.
